### ISSUE TITLE
Potential regression caused by #110

### ISSUE THREAD

**Issue by emmenko** [changesets/action#114]
It seems that the latest changes merged from #110 are causing the release process to fail.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/1110551/141267343-4fba08c7-cefc-49ca-afa6-796bce3088bb.png">

If I pin the GH action to the previous commit `b98cec97583b917ff1dc6179dd4d230d3e439894` instead of `changesets/action@master` it works fine.

Not sure how the changes related to `.npmrc` are causing this issue 🤔. @Andarist any idea maybe?

Also, I noticed that there is something odd with the if-else logic. In my setup I do have the `.npmrc` file with the auth token but I see the message log `Didn't find existing auth token for the npm registry in the user .npmrc file, creating one`.

<img width="852" alt="Screen Shot 2021-11-11 at 09 52 14" src="https://user-images.githubusercontent.com/1110551/141267991-ed3b862e-6ca0-4603-855b-af2d32a4d3b3.png">

Let me know if I can help solving this. Thanks

**Comment by Andarist** [comment]
>  In my setup I do have the .npmrc file

Where your `.npmrc` file is located?

For my own reference:
[failed job](https://github.com/commercetools/merchant-center-application-kit/runs/4175612973?check_suite_focus=true)
[successful job](https://github.com/commercetools/merchant-center-application-kit/runs/4175800534?check_suite_focus=true)

**Comment by Andarist** [comment]
It indeed seems like the check for the authToken has failed for some reason. I'm not yet sure how because what you put there seems to match the regexp. My bet is that you have additional whitespace at the beginning of your line with the token and thus the `^` in the regexp prevents that from matching. I thought that the leading whitespace was not allowed there. 

Could you check if that is the case?

**Comment by emmenko** [comment]
Yes you're right, there are indeed whitespaces

<img width="415" alt="image" src="https://user-images.githubusercontent.com/1110551/141272995-3e6aaeb4-f769-4a96-9dc5-1a819c95cd96.png">

**Comment by Andarist** [comment]
Ok, great - and I assume this is allowed since u were using it successfully before. 

Could u prepare a PR with a fix for that? Just add "any amount of whitespace" after `^` in the regexp. I could then release it from mobile by merging the PR cause im not at the computer right now

**Comment by emmenko** [comment]
Sure, I can adjust the regex. Thanks for the help!

**Comment by emmenko** [comment]
Btw, do you think this is also related to the actual JSON.parse error? 🤔

**Comment by Andarist** [comment]
It might be - my guess is that its failing on parsing the authentication error there since it ends up in the stderr but we only try to parse stdout. Different npm versions put errors in either stdout or stderr - which is super inconvenient for us to handle.

I plan to rework how we publish packages this week (or next week) and I will take a look at solving this too.

**Comment by emmenko** [comment]
@Andarist alright, I created a PR with the fix and some refactoring.

**Comment by Andarist** [comment]
Fixed by https://github.com/changesets/action/pull/116
