### ISSUE TITLE
Cannot Parse Package Informations in GHA

### ISSUE THREAD

**Issue by valpinkman** [changesets/action#158]
Hello there,

I've been trying to setup your Action with the Github Bot. I made a very simple repo to test it out. Yet it seems everytime the action runs, it breaks on the `changeset version` script, with error not being able to parse project informations.

Here is a github action run to demonstrate. https://github.com/valpinkman/changeset-test/runs/5420902223?check_suite_focus=true

I hope it's not a config issue from me but I cannot where I'm getting things wrong.

Maybe someone can point me in the right direction ? 

Thanks

**Comment by Andarist** [comment]
It's because those 2 changesets refer to the packages that don't exist:
https://github.com/valpinkman/changeset-test/blob/70a69b22d4d91b7910c8adfa612485dee7bcbe19/.changeset/fuzzy-goats-roll.md
https://github.com/valpinkman/changeset-test/blob/70a69b22d4d91b7910c8adfa612485dee7bcbe19/.changeset/proud-mice-wink.md

The error message here probably could be better.
