### ISSUE TITLE
`createGithubReleases` not work if I release my package to docker hub

### ISSUE THREAD

**Issue by zanminkian** [changesets/action#260]
Some repos which release its output to docker hub or vscode extension marketplace use its own release script. The release script probably will not print `New tag:`. So `createGithubReleases` will not work even though I set it to `true`. This bug caused by [this line](https://github.com/changesets/action/blob/8c3f5f5637a95a2327e78d5dabcf357978aedcbb/src/run.ts#L139).

**Comment by zanminkian** [comment]
I have to add `&& echo "New tag:"` at the end of the release script, which is a ugly workaround.

**Comment by marcovanharten-cpi** [comment]
@zanminkian . I think that is indeed referring to the stdout that `npx changeset tag` produces: 
![image](https://github.com/changesets/action/assets/114489263/f49d1cce-b13a-45f5-91eb-a1e4f9242633)

If there is no particular reason you are not tagging in the release script, for me it did fix everything by just updating the release script as follows:
```json
{
  "release": "... && pnpm publish && changeset tag"
}
```

Hopefully this helps your workflow as well, although I think if this is the "expected behavior", they should mention this more clearly in the docs

**Comment by zanminkian** [comment]
@marcovanharten-cpi Many thanks! Docs should tell use clearly.

**Comment by manuel3108** [comment]
Happend to me just now. This should really be mentioned in the readme.

**Comment by Andarist** [comment]
@manuel3108 PRs are welcome

**Comment by manuel3108** [comment]
#345
