### ISSUE TITLE
How many action codebases?

### ISSUE THREAD

**Issue by Noviny** [changesets/action#3]
Is it better to have one changesets GH action that's configurable with multiple actions, vs having different things for different tasks. The way this was initially set up, I thought we were going to be getting one package, but we've since divided. What's the reasons? Technical or philosophical?

Hypothesis: As a user, it would be good to be able to add the `changesets` github actions, the configure in one file what actions of it I use.

Downside: Shipping/loading unnecessary code + doing unnecessary work

**Comment by mitchellhamilton** [comment]
They’re each doing quite different things with different constraints.

The main thing being that the release action executes user code and trusts that the user code is safe since it’s only run on the base repo code which is important because sensitive secrets are passed.

The check action on the other hand doesn’t execute any user code, it also doesn’t need to be setup with the whole environment of the repo which we need to do because otherwise we’d be exposing a GitHub token to PRs which would Be Bad.

—-

I think it might be possible to write both workflows in one file though, I’ll look into it.

**Comment by mitchellhamilton** [comment]
Since we only have one action now, I think we can close this
