### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by calebeby** [changesets/action#51]
Hi! Soon after setting this up I got an email from GitHub:

> Hi @calebeby,
>
> On August 14th, 2020 at 19:49 (UTC) your personal access token (____) using node-fetch/1.0 (+https://github.com/bitinn/node-fetch) was used as part of a query parameter to access an endpoint through the GitHub API:
>
> https://api.github.com/graphql
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

Can you switch out the authentication method so that this action still continues to work in the future?

**Comment by Andarist** [comment]
Thanks for the report - we'll handle this asap. It seems that we just need to upgrade GitHub-related dependencies (like octokit) because we do not interact with the GitHub API directly ourselves.

**Comment by calebeby** [comment]
Yep: https://github.com/calebeby/eslint-config/blob/master/.github/workflows/release.yml

**Comment by Andarist** [comment]
Are you sure this has been caused by this action? [Your latest run](https://github.com/calebeby/eslint-config/runs/985981062?check_suite_focus=true) has happened on Fri, 14 Aug 2020 17:42:28 GMT but the message you have posted here says that the request has happened on August 14th, 2020 at 19:49 (UTC), so there is over 2h difference between those 2. I can't find in the compiled code of this action `access_token` to be used as a query param and I haven't received a similar notice, even though I have few active repositories setup with Changesets 🤔

**Comment by mitchellhamilton** [comment]
It'll be because of https://github.com/atlassian/changesets/blob/efd01d9b7a46ba2a44df1f5fdb47436e9219f44b/packages/get-github-info/src/index.ts#L75
