### ISSUE TITLE
How can I run actions on "Version Packages" PR

### ISSUE THREAD

**Issue by jeffsee55** [changesets/action#99]
Since Github workflows triggered from PRs [do not run when a PR is created](https://github.com/peter-evans/create-pull-request/issues/48) by Github actions, the required workflow to build and test before merging is not running when changeset bot creates a versioning PR. We tried to get around this with [another action](https://github.com/tinacms/tinacms/pull/1961) but weren't successful. 

Curious what others are doing to get around this?

[Our PR action](https://github.com/tinacms/tinacms/blob/main/.github/workflows/publish.yml#L45-L51)

**Comment by Andarist** [comment]
I've forwarded the feedback about this to GitHub some time ago but unfortunately, nothing has changed since then.

The only workaround, that I know of, is to create a bot-like user and use its PAT instead of the default token available in secrets. You can check out that it works for example here: https://github.com/developit/microbundle/pull/859

**Comment by jeffsee55** [comment]
Ok thanks @Andarist, we'll give that a shot!
